#!/bin/bash

#declare bash string
BASH_VAR="Bash Script"

#echo variable BASH_VAR
echo $BASH_VAR

#when meta character such as $ is escaped with "\" it will be read literally
echo \$BASH_VAR

#backslash has also special meaning and can be suppressed with yet another "\"
echo "\\"
