#!/bin/bash

echo "Add a task?"
YES="Yes"
NO="No"
CHOICE=$(gum choose "$YES" "$NO")
FULL_DATE=$(date -I)
YEAR=$(date -I | cut -d'-' -f1)
MONTH=$(date -I | cut -d'-' -f2)

if [ "$CHOICE" != "$YES" ]; then
	cat /home/$USER/Documents/Tasks/${YEAR}/${MONTH}/${FULL_DATE}_tasks.txt
	echo "Goodbye"
	exit 1
fi
mkdir -p /home/$USER/Documents/Tasks/${YEAR}/${MONTH}
gum input --placeholder "Enter your task here" >> /home/$USER/Documents/Tasks/${YEAR}/${MONTH}/${FULL_DATE}_tasks.txt
echo "Task added"
cat /home/$USER/Documents/Tasks/${YEAR}/${MONTH}/${FULL_DATE}_tasks.txt
